# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRj1-zE1LJyeyoSlAOgNQGSjHHfyWNWo
"""


import streamlit as st
import joblib
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem

# ----------------------------
# Load saved objects
# ----------------------------
model = joblib.load("polymer.pkl")
scaler = joblib.load("scaler.pkl")
encoder = joblib.load("encoder.pkl")

# ----------------------------
# SMILES → Morgan Fingerprint
# ----------------------------
def smiles_to_features(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    fp = AllChem.GetMorganFingerprintAsBitVect(
        mol,
        radius=2,
        nBits=2048
    )

    arr = np.array(fp)
    arr = arr.reshape(1, -1)

    # scale same way as training
    arr_scaled = scaler.transform(arr)

    return arr_scaled


# ----------------------------
# Streamlit UI
# ----------------------------
st.set_page_config(page_title="Polymer Classifier", layout="centered")

st.title("🔬 Polymer Type Classifier")
st.markdown("Predict polymer class from SMILES string using ML")

smiles_input = st.text_input("Enter SMILES string:")

if st.button("🚀 Predict Polymer Type"):

    if smiles_input.strip() == "":
        st.warning("Please enter a SMILES string.")
    else:
        features = smiles_to_features(smiles_input)

        if features is None:
            st.error("Invalid SMILES string. Please check input.")
        else:
            prediction = model.predict(features)
            label = encoder.inverse_transform(prediction)[0]

            st.success(f"🧪 Predicted Polymer Type: **{label}**")
